// Various text edits.
// Copyright (C) 2014 Gang Chen.

#include "text-edit.hpp"

namespace
{

enum Operator
{
    OP_INSERTION,
    OP_INSERTION_1,
    OP_INSERTION_2,
    OP_INSERTION_3,
    OP_INSERTION_4,
    OP_INSERTION_5,
    OP_INSERTION_6,
    OP_INSERTION_7,
    OP_INSERTION_8,
    OP_INSERTION_9,
    OP_INSERTION_10,
    OP_INSERTION_AT_CURSOR,
    OP_INSERTION_1_AT_CURSOR,
    OP_INSERTION_2_AT_CURSOR,
    OP_INSERTION_3_AT_CURSOR,
    OP_INSERTION_4_AT_CURSOR,
    OP_INSERTION_5_AT_CURSOR,
    OP_INSERTION_6_AT_CURSOR,
    OP_INSERTION_7_AT_CURSOR,
    OP_INSERTION_8_AT_CURSOR,
    OP_INSERTION_9_AT_CURSOR,
    OP_INSERTION_10_AT_CURSOR,
    OP_REMOVAL,
    OP_REMOVAL_BEFORE_CURSOR,
    OP_REMOVAL_1_BEFORE_CURSOR,
    OP_REMOVAL_2_BEFORE_CURSOR,
    OP_REMOVAL_3_BEFORE_CURSOR,
    OP_REMOVAL_4_BEFORE_CURSOR,
    OP_REMOVAL_5_BEFORE_CURSOR,
    OP_REMOVAL_6_BEFORE_CURSOR,
    OP_REMOVAL_7_BEFORE_CURSOR,
    OP_REMOVAL_8_BEFORE_CURSOR,
    OP_REMOVAL_9_BEFORE_CURSOR,
    OP_REMOVAL_10_BEFORE_CURSOR,
    OP_REMOVAL_AFTER_CURSOR,
    OP_REMOVAL_1_AFTER_CURSOR,
    OP_REMOVAL_2_AFTER_CURSOR,
    OP_REMOVAL_3_AFTER_CURSOR,
    OP_REMOVAL_4_AFTER_CURSOR,
    OP_REMOVAL_5_AFTER_CURSOR,
    OP_REMOVAL_6_AFTER_CURSOR,
    OP_REMOVAL_7_AFTER_CURSOR,
    OP_REMOVAL_8_AFTER_CURSOR,
    OP_REMOVAL_9_AFTER_CURSOR,
    OP_REMOVAL_10_AFTER_CURSOR
};

}

namespace Samoyed
{

namespace TextFileRecover
{
}

}
